//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPracticeService.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using AppPracticeService.Pattern.Ef6;
    
    public partial class MarcAppEntities : DataContext
    {
        public MarcAppEntities()
            : base("name=MarcAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<T_City> T_City { get; set; }
        public virtual DbSet<T_Order> T_Order { get; set; }
        public virtual DbSet<T_OrderDetail> T_OrderDetail { get; set; }
        public virtual DbSet<T_OrderHistory> T_OrderHistory { get; set; }
        public virtual DbSet<T_OrderStatus> T_OrderStatus { get; set; }
        public virtual DbSet<T_Picture> T_Picture { get; set; }
        public virtual DbSet<T_Product> T_Product { get; set; }
    }
}
