//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPracticeService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public System.Guid OrderDetailId { get; set; }
        public Nullable<System.Guid> OrderId { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public Nullable<double> ProductPrice { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
