//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPracticeService.Data
{
    using System;
    using System.Collections.Generic;
    
    using AppPracticeService.Pattern.Ef6;
    public partial class Size : Entity
    {
        public Size()
        {
            this.T_Product = new HashSet<T_Product>();
        }
    
        public System.Guid SizeId { get; set; }
        public string SizeCode { get; set; }
        public string SizeName { get; set; }
        public string SizeType { get; set; }
        public string SizeGroup { get; set; }
        public Nullable<int> FontSize { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<T_Product> T_Product { get; set; }
    }
}
