//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPracticeService.Data
{
    using System;
    using System.Collections.Generic;
    
    using AppPracticeService.Pattern.Ef6;
    public partial class T_OrderHistory : Entity
    {
        public System.Guid OrderHistoryId { get; set; }
        public Nullable<System.Guid> OrderId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> OrderStatusId { get; set; }
        public string HistoryDescription { get; set; }
        public Nullable<bool> Active { get; set; }
        public int HistoryStep { get; set; }
    
        public virtual T_Order T_Order { get; set; }
        public virtual T_OrderStatus T_OrderStatus { get; set; }
    }
}
